import React, { ReactElement, useEffect } from 'react'
import { Provider, useDispatch } from 'react-redux'
import Head from 'next/head'
import Header from './components/Header'
import Footer from './components/Footer'
import { store } from '../redux/store'
import { getStatusRequest } from '../redux/actions/status'

function App(props: { children: ReactElement }) {
  const { children } = props
  const dispatch = useDispatch()

  useEffect(() => {
    dispatch(getStatusRequest())
  }, [])
  return (
    <div className="App">
      <Head>
        <title>My-NextJs-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"
          integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
        <link
          href="http://fonts.cdnfonts.com/css/adobe-clean"
          rel="stylesheet"
        />
      </Head>

      <Provider store={store}>
        <Header />
        <main>{children}</main>
        <Footer />
      </Provider>
    </div>
  )
}

export default App
